version: '3.8'

services:
  wireguard:
    image: linuxserver/wireguard:latest
    container_name: wireguard-server
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    privileged: true  # WireGuard 인터페이스 관리를 위한 권한
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Seoul
      - SERVERURL=localhost  # 로컬 테스트용
      - SERVERPORT=51820
      - PEERS=100
      - PEERDNS=auto
      - INTERNAL_SUBNET=10.100.0.0/16
      - ALLOWEDIPS=10.100.0.0/16
      - LOG_CONFS=true
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    restart: unless-stopped
    networks:
      vpn_net:
        ipv4_address: 172.20.0.2

  vpn-api:
    build: ./api
    container_name: vpn-api
    environment:
      - DATABASE_URL=postgresql://vpn:vpnpass@postgres:5432/vpndb
      - WIREGUARD_CONFIG_PATH=/config
      - API_PORT=8090
      - API_TOKEN=test-token-123  # 로컬 테스트용 토큰
      - SERVERURL=localhost
    volumes:
      - ./config:/config
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8090:8090
    depends_on:
      - postgres
      - wireguard
    restart: unless-stopped
    networks:
      vpn_net:
        ipv4_address: 172.20.0.3

  postgres:
    image: postgres:15
    container_name: vpn-postgres
    environment:
      - POSTGRES_DB=vpndb
      - POSTGRES_USER=vpn
      - POSTGRES_PASSWORD=vpnpass
    volumes:
      - vpn_db_data:/var/lib/postgresql/data
    ports:
      - 5433:5432  # 로컬 테스트용 다른 포트
    restart: unless-stopped
    networks:
      vpn_net:
        ipv4_address: 172.20.0.4

  # 선택사항: WireGuard UI (로컬 테스트용)
  wireguard-ui:
    image: ngoduykhanh/wireguard-ui:latest
    container_name: wireguard-ui
    environment:
      - SENDGRID_API_KEY=
      - EMAIL_FROM_ADDRESS=
      - EMAIL_FROM_NAME=
      - SESSION_SECRET=test-session-secret
      - WGUI_USERNAME=admin
      - WGUI_PASSWORD=admin123
      - WGUI_ENDPOINT_ADDRESS=localhost
      - WGUI_DNS=8.8.8.8
      - WGUI_MTU=1420
      - WGUI_PERSISTENT_KEEPALIVE=25
      - WGUI_CONFIG_FILE_PATH=/config/wg0.conf
    volumes:
      - ./config:/config
    ports:
      - 5000:5000
    depends_on:
      - wireguard
    networks:
      vpn_net:
        ipv4_address: 172.20.0.5

networks:
  vpn_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24

volumes:
  vpn_db_data: